title: Powered by Nginx
description: "Support nginx and free software against unlawful pressure"
baseurl: ""
url: "https://poweredbynginx.org"
github_repo: komachi/poweredbynginx
theme: minima

twitter:
  username: antnesterov
  card: summary

languages:
  - name: English
    link: '/'
    code: en
  - name: Русский
    link: '/ru'
    code: ru

gems:
  - jekyll-seo-tag
  - jekyll-sitemap